= obazl_hello
:toc: true

A Minimal Working Example demonstrating the use of

* link:https://github.com/obazl/rules_ocaml[rules_ocaml]
* link:https://github.com/obazl/tools_opam[tools_opam]

== Getting started

link:https://bazel.build/install[Install Bazel].  Then:

    git clone https://github.com/obazl/obazl_hello.git
    cd obazl_hello
    bazel test //... --build_tests_only

You'll see some messages the first time you build, while the extension configures a local opam switch; for example:

     Fetching module extension @@tools_opam+//extensions:opam.bzl%opam; Building @tools_opam//extensions/config
     Fetching ... @@tools_opam+//extensions:opam.bzl%opam; Creating local switch for compiler 5.3.0 at /path/to/obazl_hello 54s
    Fetching module extension @@tools_opam+//extensions:opam.bzl%opam; Installing pkg ounit2 (0 of 1) 15s

You can run the tests individually:

    bazel test src/hello:test
    bazel test src/goodbye:test

NOTE: This is an alpha version. There is still some flakiness in some
situations involving opam commands (like creating a switch) that I
haven't worked out. If you see error messages, try running the build
again. You may need to run `bazel clean --expunge`. Once your switch
is properly configured (which you can do manually if you prefer), you
should not see such errors.  If you do, please file an issue.

The `tools_opam` module extension `opam` supports three different
toolchain strategies, `local`, `global`, and `xdg`. See
link:https://github.com/obazl/tools_opam[tools_opam] for more
information and instructions on how to use them.

