= demo_hello
:toc: true

A Minimal Working Example demonstrating the use of link:https://github.com/obazl/rules_ocaml[rules_ocaml] and link:https://github.com/obazl/tools_opam[tools_opam].

== Getting started

link:https://bazel.build/install[Install Bazel,window=_blank].  Then:

    git clone https://github.com/obazl/demo_hello.git
    cd demo_hello
    bazel run bin:hello
    bazel test test
    bazel build //...    #  builds all targets

You'll see some messages the first time you build, while the extension configures a local opam switch; for example:

     Fetching module extension @@tools_opam+//extensions:opam.bzl%opam; Building @tools_opam//extensions/config
     Fetching ... @@tools_opam+//extensions:opam.bzl%opam; Creating local switch for compiler 5.3.0 at /path/to/obazl_hello 54s
    Fetching module extension @@tools_opam+//extensions:opam.bzl%opam; Installing pkg ounit2 (0 of 1) 15s

You can build targets individually:

    bazel test lib/hello:Hello
    bazel test lib/goodbye:Goodbye

The `tools_opam` module extension `opam` supports three different
toolchain strategies, `local`, `global`, and `xdg`. See
link:https://github.com/obazl/tools_opam[tools_opam] for more
information and instructions on how to use them.

== Exercising the OCaml compilers

The standard OCaml distribution comes with four basic compilers
(`+ocamlopt.opt`, `+ocamlc.byte+`, `+ocamlopt.byte`, and
`+ocamlc.opt`) plus a profiling frontend (`+ocamlcp+`). Furthermore,
the compilers may be configured in a variety of ways: with a
`+debug-runtime+`, or the flambda optimizer, and so forth.

The OBazl rules (`+rules_ocaml+`) support the four basic compilers out
of the box. You can choose one by passing
`--@rules_ocaml//toolchain=<tc>`, where `<tc>` is one of `ocamlopt`,
`ocamlopt.opt`, `ocamlc`, `ocamlc.byte`, `ocamlopt.byte`, and
`ocamlc.opt`.  For example,

    $ bazel test test --@rules_ocaml//toolchain=ocamlc

You can shorten this by defining a flag alias. Put this in a bazelrc
file (see link:.bazelrc)

    common --flag_alias=tc=@rules_ocaml//toolchain

Then you can run:

    $ bazel test test --tc=ocamlc

By default, Bazel reads a variety of `+bazelrc+` files, such as
`+$HOME/.bazelrc+` and `+<projroot>/.bazelrc+`. (See
link:https://bazel.build/run/bazelrc[Write bazelrc configuration
files] for more information.) This may induce a dependency on the
local system, so to prepare a project for release you need to build
and test everything without depending on such files. That is the
purpose of such start-up options as `+--nohome_rc+`,
`+--nosystem_rc+`, etc. (Run `$ bazel startup_options help` to see a
list of all startup options.)

As an example of one way to do this, see link:tools/release_build[tools/release_build] and link:tools/release_test[tools/release_test].

Note that:

* `+$ bazel test //...+` will build all targets and run all tests
* `+$ bazel test //... --build_tests_only+` will run all tests but only build targets required by the tests
